# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36645b94af8a9f609b408b12876136ddca964b16a8ab9a7f1a4a8ac8eb532ccd6e4c188bc659b7d285977debf89bf790369303540b4e12ddfb14b027d0bf05dc

test:
  secret_key_base: 224e181373c91afdef46966a76f9016016ff3378e7f79f3f2bf2860cab72bcefaf099f81fdcb8b48e1b84b7227b4308fb812ffb5dbcccda687fef2c5e78e1cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
